./fdf test_maps/10-2.fdf
./fdf test_maps/10-70.fdf
./fdf test_maps/100-6.fdf
./fdf test_maps/20-60.fdf
./fdf test_maps/42.fdf
./fdf test_maps/42subject.fdf
./fdf test_maps/50-4.fdf
./fdf test_maps/basictest.fdf
./fdf test_maps/debug.fdf
./fdf test_maps/elem-col.fdf
./fdf test_maps/elem-fract.fdf
./fdf test_maps/elem.fdf
./fdf test_maps/elem2.fdf
./fdf test_maps/julia.fdf
./fdf test_maps/mars.fdf
./fdf test_maps/pentenegpos.fdf
./fdf test_maps/plat.fdf
./fdf test_maps/pnp_flat.fdf
./fdf test_maps/pylone.fdf
./fdf test_maps/pyra.fdf
./fdf test_maps/pyramide.fdf
./fdf test_maps/t1.fdf
./fdf test_maps/t2.fdf
